name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
        php:
          - 8.5
          - 8.4
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-file: development
          ini-values: phar.readonly=off
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
      - run: composer build
      - run: composer require symfony/console:^8.0 --dry-run --working-dir=tests/install-as-dep
      - run: composer require symfony/console:^7.0 --dry-run --working-dir=tests/install-as-dep
      - run: composer require symfony/console:^6.0 --dry-run --working-dir=tests/install-as-dep
      - run: cd tests/install-as-dep && composer install && php query.php
      - run: cd tests/install-as-dep && php -d phar.readonly=0 vendor/bin/phar-composer build . query.phar && php query.phar
